title: Go Beginners' Essentials
description: Introduction to Go for programmers
theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - head.html
